import * as fs from "fs";
import * as path from "path";

/**
 * Copies the compiled ABI and the recorded deployment address into the
 * frontend as a single typed module. Run after every deploy so the app and
 * the chain can never drift apart.
 */

const ROOT = path.join(__dirname, "..");
const NETWORK = process.env.SYNC_NETWORK || "baseSepolia";

const artifactPath = path.join(
  ROOT,
  "artifacts/contracts/SoulboundCertificate.sol/SoulboundCertificate.json"
);
const deploymentPath = path.join(ROOT, "deployments", `${NETWORK}.json`);
const outPath = path.join(ROOT, "frontend/lib/contract.ts");

if (!fs.existsSync(artifactPath)) {
  throw new Error("No artifact found. Run: npm run compile");
}
if (!fs.existsSync(deploymentPath)) {
  throw new Error(`No deployment for "${NETWORK}". Run: npm run deploy`);
}

const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
const deployment = JSON.parse(fs.readFileSync(deploymentPath, "utf8"));

const file = `// AUTO-GENERATED by \`npm run sync:abi\` - do not edit by hand.
// Regenerate after every deploy so the address and ABI stay in sync.

export const CONTRACT_ADDRESS =
  "${deployment.address}" as \`0x\${string}\`;

export const CHAIN_ID = 84532; // Base Sepolia

export const GENESIS_ISSUER_NAME = ${JSON.stringify(
  deployment.genesisIssuerName
)};

export const EXPLORER_URL = "https://sepolia.basescan.org";

export const SOULBOUND_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, file);

console.log("Wrote", path.relative(ROOT, outPath));
console.log("  address:", deployment.address);
console.log("  network:", NETWORK);
console.log("  abi entries:", artifact.abi.length);
